services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - user-service
      - product-catalog-service
      - shopping-cart-service
      - order-service
      - notification-service
      - payment-service
    networks:
      - ecommerce-net

  user-service:
    build: ./services/user-service
    env_file:
      - ./services/user-service/.env
    ports:
      - "3001:3001"
    networks:
      - ecommerce-net
    restart: always

  product-catalog-service:
    build: ./services/product-catalog-service
    env_file:
      - ./services/product-catalog-service/.env
    ports:
      - "3002:3002"
    networks:
      - ecommerce-net
    restart: always

  shopping-cart-service:
    build: ./services/shopping-cart-service
    env_file:
      - ./services/shopping-cart-service/.env
    ports:
      - "3003:3003"
    networks:
      - ecommerce-net
    restart: always

  order-service:
    build: ./services/order-service
    env_file:
      - ./services/order-service/.env
    ports:
      - "3004:3004"
    networks:
      - ecommerce-net
    restart: always

  notification-service:
    build: ./services/notification-service
    env_file:
      - ./services/notification-service/.env
    ports:
      - "3005:3005"
    networks:
      - ecommerce-net
    depends_on:
      - rabbitmq
    restart: always

  payment-service:
    build: ./services/payment-service
    env_file:
      - ./services/payment-service/.env
    ports:
      - "3006:3006"
    networks:
      - ecommerce-net
    restart: always

  postgres:
    image: postgres:14
    env_file:
      - ./postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq/.env
    networks:
      - ecommerce-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    env_file:
      - ./elasticsearch/.env
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - ecommerce-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.3
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - ecommerce-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  pgdata:
  esdata:
