FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Copy Prisma schema and env before generating client
COPY src/prisma ./src/prisma

# Generate Prisma client
RUN npx prisma generate --schema=src/prisma/schema.prisma

# Copy the rest of the application files
COPY . .

RUN npm run build

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate deploy --schema=src/prisma/schema.prisma && node dist/main.js"]