FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
COPY src/prisma ./src/prisma
COPY .env .env

RUN npx prisma generate --schema=src/prisma/schema.prisma

COPY . .

RUN npm run build

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate deploy --schema=src/prisma/schema.prisma && node dist/main.js"]